### PR TITLE
Additions to performance PR

### PR DESCRIPTION
**Pull request by lzaslav**
Hi Andrew,

Thank you for creating a performance PR for ISO plugin. After looking at your PR I see two distinct parts: first is to use integer value of DDI to avoid constant conversion from string to integer in all LINQ predicates and second to cache spatial row values by id.

The first part works great and does significantly improve performance of processing large data sets. The second one doesn't improve performance that much. Upon analyzing the code to understand why it is slow, I realized that majority of time is spent reading binary files over and over again when mapping sections and creating working datas. For each of the working data in the same section, binary files are being read to find first rows that have value for that working data. That's where the majority of slowdown happens.

My changes (second commit of this PR) optimizes this by loading all rows from binary files once per each section. That does bring in improvement in processing of large datasets especially if some TLG files have exactly 255 DLVs (working data) in them.

Please let me know how you would like to proceed in getting this changes in your PR and eventually into ISO plugin repo.

### CODE REVIEW

**Comment by adv12** [comment]
Hi Leo.

Thanks for following up on my PR.

I agree with your assessment that the biggest performance gains are captured in your first commit.  If I remember right, those changes took my time down from 54min to ~3min, and the remaining changes brought it down to just under 2min.

You can understand how, once you're at 3min, saving 1/3 of your import time still feels like a big deal.  But I'm not super particular as long as we get what's in your first commit.

I'd like to test your changes just to make sure everything works on our end, but I think I may need them submitted differently.  You made the changes in your develop branch and made a PR from that into my ImportPerformance branch, which has similar changes, and now it's not clear which changes are mine and which are yours.  From my limited experience with Git/GitHub, the way this typically goes is you create a branch off of my branch specifically for the changes you want to submit to me.  Then you make your changes in that branch and create a PR against my branch from it, and everything merges all slick-like and I can see a diff with your changes to my code.  Would it be possible for you to follow that process and submit a new PR?

**Comment by lzaslav** [comment]
Hi Andrew,

Thank you for providing feedback. It does make sense that any improvement above 10% is a big deal no matter how small it is in absolute values. Hopefully proposed changes are in line with your improvements.

I've redid my branch off yours and force pushed it to git so now there is a single commit containing proposed changes and is easy to review.

**Comment by adv12** [comment]
Leo,

Thanks for modifying your PR to make it easier to follow.

Sorry it's taken me over a week to get to this--got stuck on another problem at work.

I tried your develop branch with the ISO card I've been working with.  It took 3.70 minutes to import into our application.

This seemed longer than I remembered it taking before I introduced the SpatialValuesById array in ISOSpatialRow.  So on my local copy of my branch, I rolled back just the list-to-array changes, and it imported in 3.03 minutes.

Did you do speed comparisons between my version minus the SpatialValuesById array and your final version?  The data seem to show a slowdown.

Here's a flame graph of the import with my slightly-rolled-back version:

MyFlameGraph

The chunk on the right is essentially the plugin.Import() step.

Here's yours:

LeosFlameGraph

Notice the extra chunk under SectionMapper.Map().

If it's OK, I think I'd rather commit and push my rollback than accept this PR.

**Comment by lzaslav** [comment]
Hi Andrew,

Thank you for detailed analysis of proposed changes. There was a missing code in my PR (I forgot to actually use `isoRecordsWithData` variable after it was loaded with data). Once that change was made, I compared the performance my timing it against your original changes and can definitely see improvements. Please accept my apologies regarding that omission.

**Pull request merged**
